/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Notas;

import java.text.DecimalFormat;

public class calculo extends javax.swing.JFrame {
    
   
    /**
     * Creates new form calculo
     */
    public calculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnot1 = new javax.swing.JTextField();
        txtnot2 = new javax.swing.JTextField();
        txtnot3 = new javax.swing.JTextField();
        txtevaf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblpnf = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblnd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbln2 = new javax.swing.JLabel();
        lbln3 = new javax.swing.JLabel();
        lblef = new javax.swing.JLabel();
        lbln1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Nota 1: 15%");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 70, 110, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Nota 2: 20%");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 102, 103, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("Nota 3: 25%");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 137, 120, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Evaluación Final: 40%");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(48, 178, 175, 22);

        txtnot1.setCaretColor(new java.awt.Color(255, 0, 204));
        txtnot1.setDisabledTextColor(new java.awt.Color(255, 255, 0));
        txtnot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnot1ActionPerformed(evt);
            }
        });
        txtnot1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnot1KeyTyped(evt);
            }
        });
        getContentPane().add(txtnot1);
        txtnot1.setBounds(250, 60, 79, 30);

        txtnot2.setDisabledTextColor(new java.awt.Color(255, 204, 51));
        getContentPane().add(txtnot2);
        txtnot2.setBounds(250, 100, 79, 30);

        txtnot3.setDisabledTextColor(new java.awt.Color(255, 255, 0));
        getContentPane().add(txtnot3);
        txtnot3.setBounds(250, 140, 79, 30);

        txtevaf.setDisabledTextColor(new java.awt.Color(204, 204, 0));
        getContentPane().add(txtevaf);
        txtevaf.setBounds(250, 180, 79, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Nota Evaluación Final");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 330, 210, 22);

        lblpnf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblpnf.setText("0");
        getContentPane().add(lblpnf);
        lblpnf.setBounds(110, 360, 110, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 0));
        jLabel6.setText("Nota Definitiva");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 320, 160, 22);

        lblnd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblnd.setText("0.0");
        getContentPane().add(lblnd);
        lblnd.setBounds(490, 350, 140, 29);

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 360, 110, 30);

        lbln2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbln2.setText("0");
        getContentPane().add(lbln2);
        lbln2.setBounds(360, 100, 120, 29);

        lbln3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbln3.setText("0");
        getContentPane().add(lbln3);
        lbln3.setBounds(360, 130, 110, 29);

        lblef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblef.setText("0");
        getContentPane().add(lblef);
        lblef.setBounds(360, 170, 120, 29);

        lbln1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbln1.setText("0");
        getContentPane().add(lbln1);
        lbln1.setBounds(360, 60, 120, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("formulario calificacion de estudiantes");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 10, 620, 58);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(31, 0, 54, 36);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notas/ellipse-784353_960_720.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-10, -6, 720, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DecimalFormat formato = new DecimalFormat("0.00");   
        
        double not1, not2, not3, evafi;
        double porcentnot1, porcentnot2, porcentnot3, porcentevafi, porcentpef, nd;
        
        //nota1
        not1 = Double.parseDouble(txtnot1.getText());
        porcentnot1 = not1 * 0.15;
        String pn1 = formato.format(porcentnot1);
        lbln1.setText(pn1);
        
        //nota2
        not2 = Double.parseDouble(txtnot2.getText());
        porcentnot2 = not2 * 0.20;    
        String pn2 = formato.format(porcentnot2);
        lbln2.setText(pn2);
        
        //nota3
        not3 = Double.parseDouble(txtnot3.getText());
        porcentnot3 = not3 * 0.25;    
        String pn3 = formato.format(porcentnot3);
        lbln3.setText(pn3);
        
        //evaluación final
        evafi = Double.parseDouble(txtevaf.getText());
        porcentevafi = evafi * 0.40;    
        String pevf = formato.format(porcentevafi);
        lblef.setText(pevf);
        
        porcentpef = (3.5 - (porcentnot1 + porcentnot2 + porcentnot3))/0.4;
        String pef = formato.format(porcentpef);
        lblpnf.setText(pef);
        
        nd = porcentnot1 + porcentnot2 + porcentnot3 + porcentevafi;
        
        String ndd = formato.format(nd);
        lblnd.setText(ndd);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnot1ActionPerformed

    private void txtnot1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnot1KeyTyped
       
    }//GEN-LAST:event_txtnot1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblef;
    private javax.swing.JLabel lbln1;
    private javax.swing.JLabel lbln2;
    private javax.swing.JLabel lbln3;
    private javax.swing.JLabel lblnd;
    private javax.swing.JLabel lblpnf;
    private javax.swing.JTextField txtevaf;
    private javax.swing.JTextField txtnot1;
    private javax.swing.JTextField txtnot2;
    private javax.swing.JTextField txtnot3;
    // End of variables declaration//GEN-END:variables
}
